// Generated by https://quicktype.io

export interface ProductSearch {
  id:          number;
  title:       string;
  price:       number;
  description: string;
  images:      string[];
  creationAt:  string;
  updatedAt:   string;
  category:    Category;
}

export interface Category {
  id:         number;
  name:       string;
  image:      string;
  creationAt: string;
  updatedAt:  string;
}
